const API_URL="https://script.google.com/macros/s/AKfycbx7gcSCqv4BNrzXpcVMrJnvYvJwR7xbL3Yus0MdtLjmD5wASeKqEj0JxrtkffojFQ/exec";
const SESSION_KEY="bloodDonationUser";
let user=JSON.parse(localStorage.getItem(SESSION_KEY)||"null");
let settings={orgName:"Your Organization",appName:"Blood Donation App",logo:"",primary:"#b91c1c",hero:"Every drop can save a life"};
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function api(action,data={}){const payload={action,...data};const method=["login","register","registerDonor","createRequest","updateDonor","deleteDonor","updateRequest","deleteRequest","addDonation","addNotification","markNotificationRead","saveSetting","saveDashboard"].includes(action)?"POST":"GET";let r;if(method==="GET"){const q=new URLSearchParams(payload);r=await fetch(API_URL+"?"+q.toString());}else{r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});}const j=await r.json();if(!j.success)throw new Error(j.error||"Request failed");return j}
function saveSession(){localStorage.setItem(SESSION_KEY,JSON.stringify(user))}
async function loadSettings(){try{const r=await api("getSettings");settings={...settings,...Object.fromEntries(Object.entries(r.settings||{}).map(([k,v])=>[({["Organization Name"]:"orgName",["App Name"]:"appName",["Logo URL"]:"logo",["Primary Color"]:"primary",["Homepage Title"]:"hero"}[k]||k),v]))}}catch(e){}}
function shell(){document.documentElement.style.setProperty("--primary",settings.primary||"#b91c1c");document.title=settings.appName||"Blood Donation App";document.getElementById("app").innerHTML=`<header>${settings.logo?`<img class="logo" src="${esc(settings.logo)}">`:`<div class="logoText">🩸</div>`}<div><b>${esc(settings.orgName)}</b><small>${esc(settings.appName)}</small></div><nav><button onclick="home()">Home</button><button onclick="donors()">Find Blood</button><button onclick="requestForm()">Request Blood</button>${user?`<button onclick="profile()">My Account</button>`:""}<button onclick="${user&&user.role==="admin"?"admin()":"login()"}">${user&&user.role==="admin"?"Admin":"Login"}</button></nav></header><main id="main"></main><footer>${esc(settings.orgName)}</footer>`}
async function init(){await loadSettings();shell();home()}
function home(){main.innerHTML=`<section class="hero"><h1>${esc(settings.hero)}</h1><p>Find a donor, register as a donor, or request blood.</p><button class="primary" onclick="donorForm()">Become a Donor</button> <button onclick="donors()">Find Donor</button> <button class="danger" onclick="requestForm()">Emergency Request</button></section><section id="stats" class="cards"></section>`;api("getDashboardStats").then(r=>{stats.innerHTML=`<article><b>${r.stats.totalDonors}</b><span>Registered Donors</span></article><article><b>${r.stats.openRequests}</b><span>Open Requests</span></article><article><b>${r.stats.availableDonors}</b><span>Available Donors</span></article>`}).catch(()=>{})}
const groups=["A+","A-","B+","B-","AB+","AB-","O+","O-"];
function donors(){main.innerHTML=`<section class="panel"><h2>Find Blood Donor</h2><div class="filters"><select id="blood"><option value="">All Blood Groups</option>${groups.map(x=>`<option>${x}</option>`).join("")}</select><input id="district" placeholder="District"><input id="city" placeholder="City"><button class="primary" onclick="searchDonors()">Search</button></div><div id="results"></div></section>`;searchDonors()}
async function searchDonors(){results.innerHTML="<p>Searching…</p>";try{const r=await api("searchDonors",{bloodGroup:blood.value,district:district.value,city:city.value,available:true});results.innerHTML=r.donors.length?r.donors.map(x=>`<div class="row"><div><b>${esc(x.name)}</b><span>${esc(x.bloodGroup)} • ${esc(x.district)} ${esc(x.city)}</span></div><div><a href="tel:${esc(x.mobile)}">Call</a> <a target="_blank" href="https://wa.me/${esc(String(x.mobile).replace(/\D/g,''))}">WhatsApp</a></div></div>`).join(""):"<p>No available donor found.</p>"}catch(e){results.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
function donorForm(){main.innerHTML=`<section class="panel"><h2>Become a Donor</h2><form onsubmit="addDonor(event)"><input name="name" required placeholder="Full Name"><input name="mobile" required placeholder="Mobile Number"><input name="email" type="email" placeholder="Email"><select name="bloodGroup" required><option value="">Blood Group</option>${groups.map(x=>`<option>${x}</option>`).join("")}</select><select name="gender"><option value="">Gender</option><option>Male</option><option>Female</option><option>Other</option></select><input name="dob" type="date"><input name="district" required placeholder="District"><input name="city" placeholder="City"><input name="address" placeholder="Address"><input name="lastDonationDate" type="date"><select name="available"><option>Yes</option><option>No</option></select><button class="primary">Register Donor</button></form></section>`}
async function addDonor(e){e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target));await api("registerDonor",f);alert("Donor registered successfully.");home()}catch(x){alert(x.message)}}
function requestForm(){main.innerHTML=`<section class="panel"><h2>Blood Request</h2><form onsubmit="createRequest(event)"><input name="patientName" required placeholder="Patient Name"><input name="hospital" required placeholder="Hospital"><input name="contactNumber" required placeholder="Contact Number"><select name="bloodGroup" required><option value="">Required Blood Group</option>${groups.map(x=>`<option>${x}</option>`).join("")}</select><input name="unitsRequired" type="number" min="1" required placeholder="Units Required"><input name="district" required placeholder="District"><input name="location" placeholder="Location"><select name="priority"><option>Emergency</option><option>Normal</option></select><input name="requiredDate" type="date"><input name="requiredTime" type="time"><textarea name="description" placeholder="Additional information"></textarea><button class="danger">Submit Request</button></form></section>`}
async function createRequest(e){e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target));await api("createRequest",f);alert("Blood request submitted.");home()}catch(x){alert(x.message)}}
function login(){main.innerHTML=`<section class="panel small"><h2>Login</h2><form onsubmit="doLogin(event)"><input name="username" required placeholder="Username"><input name="password" required type="password" placeholder="Password"><button class="primary">Login</button></form><p>New user? <button onclick="registerForm()">Create account</button></p></section>`}
function registerForm(){main.innerHTML=`<section class="panel small"><h2>Create Account</h2><form onsubmit="doRegister(event)"><input name="name" required placeholder="Full Name"><input name="mobile" placeholder="Mobile"><input name="email" type="email" placeholder="Email"><input name="username" required placeholder="Username"><input name="password" required type="password" placeholder="Password"><button class="primary">Register</button></form></section>`}
async function doLogin(e){e.preventDefault();try{const r=await api("login",Object.fromEntries(new FormData(e.target)));user=r.user;saveSession();alert("Login successful");shell();user.role==="admin"?admin():profile()}catch(x){alert(x.message)}}
async function doRegister(e){e.preventDefault();try{await api("register",Object.fromEntries(new FormData(e.target)));alert("Account created. Please login.");login()}catch(x){alert(x.message)}}
function profile(){main.innerHTML=`<section class="panel"><h2>My Account</h2><p><b>${esc(user.name)}</b></p><p>Username: ${esc(user.username)}</p><p>Role: ${esc(user.role)}</p><button onclick="logout()">Logout</button></section>`}
function logout(){user=null;localStorage.removeItem(SESSION_KEY);shell();home()}
async function admin(){if(!user||user.role!=="admin")return login();main.innerHTML=`<section class="panel"><h2>Admin Dashboard</h2><div class="adminnav"><button onclick="admin()">Overview</button><button onclick="adminDonors()">Donors</button><button onclick="adminRequests()">Requests</button><button onclick="settingsPage()">App Settings</button><button onclick="dashboardEditor()">Dashboard Layout</button></div><div id="adminbody">Loading…</div></section>`;try{const r=await api("getDashboardStats");adminbody.innerHTML=`<div class="cards"><article><b>${r.stats.totalDonors}</b><span>Donors</span></article><article><b>${r.stats.totalRequests}</b><span>Requests</span></article><article><b>${r.stats.emergencyRequests}</b><span>Emergency</span></article><article><b>${r.stats.totalDonations}</b><span>Donations</span></article></div>`}catch(e){adminbody.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
async function adminDonors(){main.innerHTML=`<section class="panel"><h2>Manage Donors</h2><div id="adminbody">Loading…</div><button onclick="admin()">Back</button></section>`;try{const r=await api("getDonors");adminbody.innerHTML=r.donors.map(x=>`<div class="row"><div><b>${esc(x.name)}</b><span>${esc(x.bloodGroup)} • ${esc(x.mobile)} • ${esc(x.district)}</span></div><button onclick="deleteDonor('${esc(x.donorId)}')">Delete</button></div>`).join("")||"<p>No donors.</p>"}catch(e){adminbody.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
async function deleteDonor(id){if(!confirm("Delete this donor?"))return;try{await api("deleteDonor",{userId:user.userId,donorId:id});adminDonors()}catch(e){alert(e.message)}}
async function adminRequests(){main.innerHTML=`<section class="panel"><h2>Manage Requests</h2><div id="adminbody">Loading…</div><button onclick="admin()">Back</button></section>`;try{const r=await api("getRequests");adminbody.innerHTML=r.requests.map(x=>`<div class="row"><div><b>${esc(x.patientName)} — ${esc(x.bloodGroup)}</b><span>${esc(x.hospital)} • ${esc(x.location)} • ${esc(x.priority)} • ${esc(x.status)}</span></div><button onclick="closeRequest('${esc(x.requestId)}')">${x.status==="Closed"?"Closed":"Close"}</button></div>`).join("")||"<p>No requests.</p>"}catch(e){adminbody.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
async function closeRequest(id){try{await api("updateRequest",{userId:user.userId,requestId:id,status:"Closed"});adminRequests()}catch(e){alert(e.message)}}
async function settingsPage(){main.innerHTML=`<section class="panel"><h2>App Settings</h2><div id="settingsForm">Loading…</div><button onclick="admin()">Back</button></section>`;try{const r=await api("getSettings");const s=r.settings||{};settingsForm.innerHTML=`<form onsubmit="saveSettings(event)"><label>Organization Name<input name="Organization Name" value="${esc(s["Organization Name"]||"")}"></label><label>App Name<input name="App Name" value="${esc(s["App Name"]||"")}" ></label><label>Logo URL<input name="Logo URL" value="${esc(s["Logo URL"]||"")}"></label><label>Primary Color<input name="Primary Color" type="color" value="${esc(s["Primary Color"]||"#b91c1c")}"></label><label>Homepage Title<input name="Homepage Title" value="${esc(s["Homepage Title"]||"")}"></label><label>Emergency Contact<input name="Emergency Contact" value="${esc(s["Emergency Contact"]||"")}"></label><label>Contact Email<input name="Contact Email" value="${esc(s["Contact Email"]||"")}"></label><label>Address<input name="Address" value="${esc(s["Address"]||"")}"></label><button class="primary">Save Settings</button></form>`}catch(e){settingsForm.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
async function saveSettings(e){e.preventDefault();try{for(const [k,v] of new FormData(e.target).entries())await api("saveSetting",{userId:user.userId,setting:k,value:v});await loadSettings();shell();admin();alert("Settings saved.")}catch(x){alert(x.message)}}
async function dashboardEditor(){main.innerHTML=`<section class="panel"><h2>Dashboard Layout</h2><div id="dash">Loading…</div><button onclick="admin()">Back</button></section>`;try{const r=await api("getDashboard");dash.innerHTML=r.dashboard.map((x,i)=>`<div class="row"><label><input type="checkbox" ${x.enabled?"checked":""} data-i="${i}"> ${esc(x.title)}</label><span>Position ${esc(x.position)}</span></div>`).join("")+`<button class="primary" onclick="saveDashboardLayout(${JSON.stringify(r.dashboard).replace(/"/g,"&quot;")})">Save Layout</button>`}catch(e){dash.innerHTML=`<p class="error">${esc(e.message)}</p>`}}
async function saveDashboardLayout(items){const boxes=[...document.querySelectorAll('#dash input[type=checkbox]')];items.forEach((x,i)=>x.enabled=boxes[i].checked);try{await api("saveDashboard",{userId:user.userId,dashboard:items});alert("Dashboard layout saved.")}catch(e){alert(e.message)}}
init().catch(e=>{document.getElementById("app").innerHTML=`<section class="panel"><h2>Unable to load app</h2><p class="error">${esc(e.message)}</p></section>`});
